Move shoulda association tests to context with subject
shoulda-matchers (4.0.0) started testing `required` qualifier of
belong_to by default (`required: true` is also default for `belong_to`
from rails 5). Consider following test:
```
class DependencyTest < ActiveSupport::TestCase
	should belong_to :version
	...
end
```
In order to test if version is a required attribute of Dependency,
a dummy record needs to be created and version is set to nil.
Not having an explicit subject meant all attr were nil, including `gem_dependency`.
This blows up `use_gem_dependency` because of `throw :abort`.
Attributes were not explicitly tested in versions before 4.0.0 and
validation hooks were not running.

fixes:
```
Failure:
DependencyTest#test_: Dependency should belong to version required:
true.
[/home/travis/build/rubygems/rubygems.org/vendor/bundle/ruby/2.6.0/gems/shoulda-context-2.0.0/lib/shoulda/context/context.rb:62]:
Expected Dependency to have a belongs_to association called version (and
for the record to fail validation if :version is unset; i.e., either the
association should have been defined with `required: true`, or there
should be a presence validation on :version)
```
```
Error:
DeletionTest#test_: Deletion should belong to user required: true. :
NoMethodError: undefined method `rubygem' for nil:NilClass
    app/models/deletion.rb:30:in `rubygem_name'
    app/models/deletion.rb:34:in `record_metadata'
```