Use set_page instead of params[:page] in stats controller
https://app.honeybadger.io/projects/40972/faults/30742663#notice-summary

ArgumentError: invalid value for Integer(): "3\">XSS"
stats_controller.rb 8 index(...)
[PROJECT_ROOT]/app/controllers/stats_controller.rb:8:in `index'