Use function to calc expected_retry_after in rack attack exp backoff tests
Fixes: NameError: undefined local variable or method
`expected_retry_after' for #<RackAttackTest:0x000000000c99e1f0>

https://travis-ci.org/github/rubygems/rubygems.org/jobs/690929419

test failing in the build was added in #2311