fix arguement error for postional args
Fixes:
SendgridWebhookTest#test_errors_if_credentials_configured_on_server_are_invalid:
ArgumentError: wrong number of arguments (given 1, expected 0; required keywords: name, password)
    app/controllers/application_controller.rb:30:in `http_basic_authenticate_with'