Fix NoMethodError: undefined method `to_i' for params[:page]
Test for this error was unintentionally removed in:
https://github.com/rubygems/rubygems.org/commit/fbd444452b687fb8b6104e9dd71ca4aabb6fde18#diff-3cabaae6ed158ff268b41a0bdcc0ce3eL67

Removed test is same as test "api search with page is not a numer".