Fix nokogiri error when running rake tasks inside docker
master is currently breaking in CI due to Nokogiri trying to load a
dynamic library:

```
LoadError: Error loading shared library liblzma.so.5: No such file or directory (needed by /usr/local/bundle/ruby/2.6.0/gems/nokogiri-1.10.5/lib/nokogiri/nokogiri.so) - /usr/local/bundle/ruby/2.6.0/gems/nokogiri-1.10.5/lib/nokogiri/nokogiri.so

/usr/local/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'

/usr/local/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
```

It appears that this library used to be shipped in the ruby alpine
docker image but is no longer the case.

This fix installs the package that holds this library so the docker
is able to run rails again