Use absolute path for aside link i18n keys
Fixes (only in tests):
```
Error:
RubygemsHelperTest#test_: RubygemsHelper should link to the badge. :
RuntimeError: Cannot use t(".links.badge") shortcut because path is not
available
    app/helpers/rubygems_helper.rb:80:in `badge_link'
    test/unit/helpers/rubygems_helper_test.rb:64:in `block in
<class:RubygemsHelperTest>'
    test/unit/helpers/rubygems_helper_test.rb:67:in `instance_exec'
    test/unit/helpers/rubygems_helper_test.rb:67:in `block in
create_test_from_should_hash'
```

@virtual_path was removed in
https://github.com/rails/rails/commit/dd7a673782f102d2b58194007bf18a8e496818e3