Move redirector middleware to lib and add require_relative
Fixes:
```
Step 11/23 : RUN RAILS_ENV=production RAILS_GROUPS=assets
SECRET_KEY_BASE=1234 bin/rails assets:precompile
 ---> Running in 01e297f81121
rails aborted!
NameError: uninitialized constant Redirector
/app/config/environments/production.rb:115:in `block in <main>'
/app/config/environments/production.rb:3:in `<main>'
/app/config/environment.rb:5:in `<main>'
Caused by:
NameError: uninitialized constant Redirector
/app/config/environments/production.rb:115:in `block in <main>'
/app/config/environments/production.rb:3:in `<main>'
/app/config/environment.rb:5:in `<main>'
Tasks: TOP => environment
(See full trace by running task with --trace)
```

We had faced similiar issue with hostess when updating to rails 6.0
and used the same fix.